<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DentalClinic.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\logo_icon.png" />
    <Resource Include="Assets\logo_icon.ico" />
    <Resource Include="Assets\logo_icon1.png" />
    <Resource Include="Assets\logo_full.png" />
  </ItemGroup>

  <ItemGroup>
    <!-- مطلوب فقط من أجل enum VisitStatus المستخدَم في StatusToBrushConverter -->
    <ProjectReference Include="..\DentalClinic.Data\DentalClinic.Data.csproj" />
  </ItemGroup>

</Project>
