<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DentalClinic.Features</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentalClinic.Data\DentalClinic.Data.csproj" />
    <ProjectReference Include="..\DentalClinic.UI\DentalClinic.UI.csproj" />
  </ItemGroup>

</Project>
