using System.Data;
using Microsoft.Data.SqlClient;
using DentalClinic.Data.Models;

namespace DentalClinic.Data.DataAccess;

// كل استعلامات اللوحة المالية - يُستخدم من تطبيق الطبيب فقط (صلاحية المدير العام تحديداً)
public class FinancialRepository
{
    private readonly DatabaseHelper _db;

    public FinancialRepository(DatabaseHelper db)
    {
        _db = db;
        EnsureClinicExpensesTableExists();
        EnsureCommissionColumnsExist();
    }

    // فئة المصاريف المخصَّصة للعمولات المُولَّدة تلقائياً - قيمة ثابتة نستخدمها للفلترة والتمييز
    public const string DoctorCommissionCategory = "Doctor Commission";

    // إضافة الأعمدة اللازمة لربط مصروف العمولة التلقائي بالجلسة/الدفعة/الطبيب المصدر، وتمييزه
    // عن المصاريف اليدوية العادية (IsAutoGenerated) - migration آمنة لقواعد البيانات القديمة
    private void EnsureCommissionColumnsExist()
    {
        const string sql = @"
            IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'IsAutoGenerated' AND Object_ID = Object_ID(N'ClinicExpenses'))
            BEGIN
                ALTER TABLE ClinicExpenses ADD IsAutoGenerated BIT NOT NULL DEFAULT 0;
            END
            IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'SourceSessionID' AND Object_ID = Object_ID(N'ClinicExpenses'))
            BEGIN
                ALTER TABLE ClinicExpenses ADD SourceSessionID INT NULL;
            END
            IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'SourcePaymentID' AND Object_ID = Object_ID(N'ClinicExpenses'))
            BEGIN
                ALTER TABLE ClinicExpenses ADD SourcePaymentID INT NULL;
            END
            IF NOT EXISTS (SELECT * FROM sys.columns WHERE Name = N'SourceDoctorUserID' AND Object_ID = Object_ID(N'ClinicExpenses'))
            BEGIN
                ALTER TABLE ClinicExpenses ADD SourceDoctorUserID INT NULL;
            END";
        _db.ExecuteNonQuery(sql);
    }

    // تسجيل مصروف عمولة طبيب تلقائي (لا يدخل عبر شاشة إضافة مصروف يدوية) - مرتبط بجلسة ودفعة محدَّدتين
    // كي يمكن تتبعه لاحقاً بدل أن يظهر كسطر عام غير مفسَّر ضمن قائمة المصاريف
    // إن وُجد فعلاً مصروف عمولة لنفس الطبيب في نفس اليوم، نُحدِّثه (نجمع المبلغ الجديد عليه) بدل
    // إنشاء صف جديد لكل دفعة - يمنع تكدّس عشرات السطور يومياً في قائمة المصاريف لكل جلسة تُحصَّل،
    // ويُبقي صفاً واحداً فقط يمثّل إجمالي عمولة ذلك الطبيب لهذا اليوم بالذات.
    public void AddDoctorCommissionExpense(decimal amount, int sessionId, int paymentId, int doctorUserId,
        string doctorName, decimal percent)
    {
        const string findSql = @"
            SELECT TOP 1 ExpenseID, Amount
            FROM ClinicExpenses
            WHERE Category = @Cat
              AND SourceDoctorUserID = @DoctorUserID
              AND CAST(ExpenseDate AS DATE) = CAST(GETDATE() AS DATE)";

        var existing = _db.ExecuteQuery(findSql,
            new SqlParameter("@Cat", DoctorCommissionCategory),
            new SqlParameter("@DoctorUserID", doctorUserId));

        var description = $"Doctor commission - Dr. {doctorName} ({percent:0.##}%) - Daily total";

        if (existing.Rows.Count > 0)
        {
            var expenseId = (int)existing.Rows[0]["ExpenseID"];
            var currentAmount = (decimal)existing.Rows[0]["Amount"];

            // بعد الدمج لم يعد الصف يمثّل جلسة/دفعة واحدة بعينها، فنُصفّر الربط بها (الحقلان أصلاً Nullable)
            const string updateSql = @"
                UPDATE ClinicExpenses
                SET Amount = @Amount, Description = @Desc, SourceSessionID = NULL, SourcePaymentID = NULL
                WHERE ExpenseID = @ExpenseID";

            _db.ExecuteNonQuery(updateSql,
                new SqlParameter("@Amount", currentAmount + amount),
                new SqlParameter("@Desc", description),
                new SqlParameter("@ExpenseID", expenseId));
        }
        else
        {
            const string insertSql = @"
                INSERT INTO ClinicExpenses (Amount, Description, Category, ExpenseDate, IsAutoGenerated, SourceSessionID, SourcePaymentID, SourceDoctorUserID)
                VALUES (@Amount, @Desc, @Cat, GETDATE(), 1, @SessionID, @PaymentID, @DoctorUserID)";

            _db.ExecuteNonQuery(insertSql,
                new SqlParameter("@Amount", amount),
                new SqlParameter("@Desc", description),
                new SqlParameter("@Cat", DoctorCommissionCategory),
                new SqlParameter("@SessionID", sessionId),
                new SqlParameter("@PaymentID", paymentId),
                new SqlParameter("@DoctorUserID", doctorUserId));
        }
    }

    // إحصائيات الأطباء المفصلة لفترة زمنية محددة.
    // النشاط (المرضى والجلسات) يعتمد على تاريخ الجلسة، بينما الإيراد يعتمد على تاريخ الدفع الفعلي.
    public List<DoctorDetailedStat> GetDetailedDoctorStatistics(DateTime fromDate, DateTime toDateExclusive)
    {
        const string sql = @"
            SELECT
                u.UserID,
                u.FullName,
                COUNT(DISTINCT CASE WHEN s.SessionDateTime >= @FromDate AND s.SessionDateTime < @ToDate THEN s.PatientID END) AS PatientCount,
                COUNT(DISTINCT CASE WHEN s.SessionDateTime >= @FromDate AND s.SessionDateTime < @ToDate THEN s.SessionID END) AS SessionCount,
                ISNULL(SUM(CASE WHEN p.PaymentDate >= @FromDate AND p.PaymentDate < @ToDate THEN p.Amount ELSE 0 END), 0) AS GrossIncome
            FROM Users u
            LEFT JOIN MedicalSessions s ON s.DoctorID = u.UserID
            LEFT JOIN Payments p ON p.SessionID = s.SessionID
            WHERE u.RoleID = 1 AND u.IsActive = 1
            GROUP BY u.UserID, u.FullName
            ORDER BY GrossIncome DESC, u.FullName";

        var table = _db.ExecuteQuery(sql,
            new SqlParameter("@FromDate", fromDate),
            new SqlParameter("@ToDate", toDateExclusive));

        var result = new List<DoctorDetailedStat>();
        foreach (DataRow row in table.Rows)
        {
            result.Add(new DoctorDetailedStat
            {
                DoctorUserId = Convert.ToInt32(row["UserID"]),
                DoctorName = row["FullName"].ToString() ?? string.Empty,
                PatientCount = Convert.ToInt32(row["PatientCount"]),
                SessionCount = Convert.ToInt32(row["SessionCount"]),
                GrossIncome = Convert.ToDecimal(row["GrossIncome"])
            });
        }

        return result;
    }

    public DoctorDetailedSummary GetDetailedDoctorSummary(DateTime fromDate, DateTime toDateExclusive, int? doctorUserId = null)
    {
        const string sql = @"
            SELECT
                COUNT(DISTINCT s.PatientID) AS PatientCount,
                COUNT(DISTINCT s.SessionID) AS SessionCount
            FROM MedicalSessions s
            WHERE s.SessionDateTime >= @FromDate AND s.SessionDateTime < @ToDate
              AND (@DoctorUserID IS NULL OR s.DoctorID = @DoctorUserID)";

        var table = _db.ExecuteQuery(sql,
            new SqlParameter("@FromDate", fromDate),
            new SqlParameter("@ToDate", toDateExclusive),
            new SqlParameter("@DoctorUserID", (object?)doctorUserId ?? DBNull.Value));

        var row = table.Rows[0];
        return new DoctorDetailedSummary
        {
            PatientCount = Convert.ToInt32(row["PatientCount"]),
            SessionCount = Convert.ToInt32(row["SessionCount"])
        };
    }

    // إحصائيات كل طبيب: عدد المرضى، عدد الجلسات، إجمالي الدخل الذي حقّقه، ونصيب كل من الطبيب والعيادة منه.
    // يشمل كل الأطباء النشطين حتى من لا نشاط له بعد (LEFT JOIN) كي تكون اللوحة معلوماتية بالكامل.
    public List<DoctorStatRow> GetDoctorStatistics()
    {
        const string sql = @"
            SELECT u.UserID, u.FullName,
                   COUNT(DISTINCT s.PatientID) AS PatientCount,
                   COUNT(DISTINCT s.SessionID) AS SessionCount,
                   ISNULL(SUM(pay.Amount), 0) AS GrossIncome
            FROM Users u
            LEFT JOIN MedicalSessions s ON s.DoctorID = u.UserID
            LEFT JOIN Payments pay ON pay.SessionID = s.SessionID
            WHERE u.RoleID = 1 AND u.IsActive = 1
            GROUP BY u.UserID, u.FullName
            ORDER BY GrossIncome DESC";

        var table = _db.ExecuteQuery(sql);
        var result = new List<DoctorStatRow>();

        foreach (DataRow row in table.Rows)
        {
            result.Add(new DoctorStatRow
            {
                DoctorUserId = (int)row["UserID"],
                DoctorName = row["FullName"].ToString()!,
                PatientCount = (int)row["PatientCount"],
                SessionCount = (int)row["SessionCount"],
                GrossIncome = (decimal)row["GrossIncome"]
            });
        }
        return result;
    }

    // إصلاح: الجدول لم يكن يُنشأ في أي مكان بالكود (بعكس TreatmentPresets) فكانت أي عملية على
    // المصاريف/صافي الربح تفشل بخطأ "Invalid object name 'ClinicExpenses'". نتّبع هنا نفس نمط
    // الإنشاء التلقائي الآمن (IF NOT EXISTS) المستخدم مع TreatmentPresets.
    private void EnsureClinicExpensesTableExists()
    {
        const string sql = @"
            IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ClinicExpenses')
            BEGIN
                CREATE TABLE ClinicExpenses (
                    ExpenseID INT IDENTITY(1,1) PRIMARY KEY,
                    Amount DECIMAL(18,2) NOT NULL,
                    Description NVARCHAR(500) NOT NULL,
                    Category NVARCHAR(100) NOT NULL DEFAULT N'General / Other',
                    ExpenseDate DATETIME NOT NULL
                );
            END";
        _db.ExecuteNonQuery(sql);
    }

    // إجمالي المداخيل (المبالغ المُحصَّلة فعلياً PaidAmount، وليس TotalPrice) - يومي/شهري/سنوي + إجمالي المتبقي
    // + نفس الفترات للمقارنة (أمس/الشهر الماضي/العام الماضي) لحساب مؤشرات الاتجاه (↑/↓) في الواجهة
    public RevenueSummary GetRevenueSummary()
    {
        const string sql = @"
            SELECT
                ISNULL(SUM(CASE WHEN CAST(pay.PaymentDate AS DATE) = CAST(GETDATE() AS DATE) THEN pay.Amount ELSE 0 END), 0) AS TodayRevenue,
                ISNULL(SUM(CASE WHEN YEAR(pay.PaymentDate) = YEAR(GETDATE()) AND MONTH(pay.PaymentDate) = MONTH(GETDATE()) THEN pay.Amount ELSE 0 END), 0) AS MonthRevenue,
                ISNULL(SUM(CASE WHEN YEAR(pay.PaymentDate) = YEAR(GETDATE()) THEN pay.Amount ELSE 0 END), 0) AS YearRevenue,
                ISNULL((SELECT SUM(TotalPrice - PaidAmount - WriteOffAmount) FROM MedicalSessions), 0) AS TotalOutstanding,
                ISNULL(SUM(CASE WHEN CAST(pay.PaymentDate AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN pay.Amount ELSE 0 END), 0) AS YesterdayRevenue,
                ISNULL(SUM(CASE WHEN YEAR(pay.PaymentDate) = YEAR(DATEADD(MONTH, -1, GETDATE())) AND MONTH(pay.PaymentDate) = MONTH(DATEADD(MONTH, -1, GETDATE())) THEN pay.Amount ELSE 0 END), 0) AS LastMonthRevenue,
                ISNULL(SUM(CASE WHEN YEAR(pay.PaymentDate) = YEAR(GETDATE()) - 1 THEN pay.Amount ELSE 0 END), 0) AS LastYearRevenue
            FROM Payments pay";

        var table = _db.ExecuteQuery(sql);
        var row = table.Rows[0];

        return new RevenueSummary
        {
            TodayRevenue = (decimal)row["TodayRevenue"],
            MonthRevenue = (decimal)row["MonthRevenue"],
            YearRevenue = (decimal)row["YearRevenue"],
            TotalOutstanding = (decimal)row["TotalOutstanding"],
            YesterdayRevenue = (decimal)row["YesterdayRevenue"],
            LastMonthRevenue = (decimal)row["LastMonthRevenue"],
            LastYearRevenue = (decimal)row["LastYearRevenue"]
        };
    }

    // كل المرضى الذين لديهم مبلغ متبقٍ غير مسدَّد، مرتّبين تنازلياً حسب الأكبر ديناً
    public List<OutstandingBalanceRow> GetOutstandingBalances()
    {
        const string sql = @"
            SELECT p.PatientID, p.FullName AS PatientFullName, p.PhoneNumber,
                   SUM(s.TotalPrice - s.PaidAmount - s.WriteOffAmount) AS TotalOwed,
                   MAX(s.SessionDateTime) AS LastVisit
            FROM MedicalSessions s
            INNER JOIN Patients p ON p.PatientID = s.PatientID
            GROUP BY p.PatientID, p.FullName, p.PhoneNumber
            HAVING SUM(s.TotalPrice - s.PaidAmount - s.WriteOffAmount) > 0
            ORDER BY TotalOwed DESC";

        var table = _db.ExecuteQuery(sql);
        var result = new List<OutstandingBalanceRow>();

        foreach (DataRow row in table.Rows)
        {
            result.Add(new OutstandingBalanceRow
            {
                PatientID = (int)row["PatientID"],
                PatientFullName = row["PatientFullName"].ToString()!,
                PhoneNumber = row["PhoneNumber"].ToString()!,
                TotalOwed = (decimal)row["TotalOwed"],
                LastVisit = (DateTime)row["LastVisit"]
            });
        }
        return result;
    }

    // عدد المرضى (الفريدين) لكل يوم خلال آخر N يوماً - أيام بلا زيارات لا تظهر في النتيجة (تُملأ لاحقاً في الواجهة)
    public List<DailyPatientCount> GetDailyPatientCounts(int days = 14)
    {
        const string sql = @"
            SELECT CAST(SessionDateTime AS DATE) AS VisitDay, COUNT(DISTINCT PatientID) AS PatientCount
            FROM MedicalSessions
            WHERE SessionDateTime >= @FromDate
            GROUP BY CAST(SessionDateTime AS DATE)
            ORDER BY VisitDay";

        var fromDate = DateTime.Now.Date.AddDays(-(days - 1));
        var table = _db.ExecuteQuery(sql, new SqlParameter("@FromDate", fromDate));

        var result = new List<DailyPatientCount>();
        foreach (DataRow row in table.Rows)
        {
            result.Add(new DailyPatientCount
            {
                Date = (DateTime)row["VisitDay"],
                Count = (int)row["PatientCount"]
            });
        }
        return result;
    }

    // أكثر النصوص تكراراً في حقل "المعالجة" - تقريب بسيط لأكثر الخدمات طلباً
    // (يعتمد على تطابق نصي حرفي، فيُنصح لاحقاً بحقل نوع علاج منظّم لدقة أعلى - هذا كافٍ كبداية عملية)
    public List<TreatmentFrequency> GetTopTreatments(int top = 5)
    {
        const string sql = @"
            SELECT TOP (@Top) TreatmentPerformed, COUNT(*) AS Cnt
            FROM MedicalSessions
            WHERE TreatmentPerformed IS NOT NULL AND LTRIM(RTRIM(TreatmentPerformed)) <> ''
            GROUP BY TreatmentPerformed
            ORDER BY COUNT(*) DESC";

        var table = _db.ExecuteQuery(sql, new SqlParameter("@Top", top));
        var result = new List<TreatmentFrequency>();

        foreach (DataRow row in table.Rows)
        {
            result.Add(new TreatmentFrequency
            {
                TreatmentText = row["TreatmentPerformed"].ToString()!,
                Count = (int)row["Cnt"]
            });
        }
        return result;
    }
    // --------------------------------------------------------
    // دوال المصاريف (Expenses) الجديدة
    // --------------------------------------------------------

    public void AddExpense(decimal amount, string description, string category, DateTime date)
    {
        const string sql = @"
        INSERT INTO ClinicExpenses (Amount, Description, Category, ExpenseDate) 
        VALUES (@Amount, @Desc, @Cat, @Date)";

        _db.ExecuteNonQuery(sql,
            new SqlParameter("@Amount", amount),
            new SqlParameter("@Desc", description),
            new SqlParameter("@Cat", category),
            new SqlParameter("@Date", date));
    }

    // تعديل مصروف موجود - نفس حقول AddExpense (Amount/Description/Category/ExpenseDate) بالتحديد،
    // بلا لمس IsAutoGenerated/SourceSessionID/SourcePaymentID/SourceDoctorUserID حتى لا ينفصل
    // مصروف عمولة الطبيب المُولَّد تلقائياً عن مصدره بعد تعديله يدوياً.
    public void UpdateExpense(int expenseId, decimal amount, string description, string category, DateTime date)
    {
        const string sql = @"
        UPDATE ClinicExpenses
        SET Amount = @Amount, Description = @Desc, Category = @Cat, ExpenseDate = @Date
        WHERE ExpenseID = @ExpenseID";

        _db.ExecuteNonQuery(sql,
            new SqlParameter("@Amount", amount),
            new SqlParameter("@Desc", description),
            new SqlParameter("@Cat", category),
            new SqlParameter("@Date", date),
            new SqlParameter("@ExpenseID", expenseId));
    }

    public ExpenseSummary GetExpenseSummary()
    {
        const string sql = @"
            SELECT
                ISNULL(SUM(CASE WHEN CAST(ExpenseDate AS DATE) = CAST(GETDATE() AS DATE) THEN Amount ELSE 0 END), 0) AS TodayExpense,
                ISNULL(SUM(CASE WHEN YEAR(ExpenseDate) = YEAR(GETDATE()) AND MONTH(ExpenseDate) = MONTH(GETDATE()) THEN Amount ELSE 0 END), 0) AS MonthExpense,
                ISNULL(SUM(CASE WHEN YEAR(ExpenseDate) = YEAR(GETDATE()) THEN Amount ELSE 0 END), 0) AS YearExpense,
                ISNULL(SUM(CASE WHEN CAST(ExpenseDate AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE) THEN Amount ELSE 0 END), 0) AS YesterdayExpense,
                ISNULL(SUM(CASE WHEN YEAR(ExpenseDate) = YEAR(DATEADD(MONTH, -1, GETDATE())) AND MONTH(ExpenseDate) = MONTH(DATEADD(MONTH, -1, GETDATE())) THEN Amount ELSE 0 END), 0) AS LastMonthExpense,
                ISNULL(SUM(CASE WHEN YEAR(ExpenseDate) = YEAR(GETDATE()) - 1 THEN Amount ELSE 0 END), 0) AS LastYearExpense
            FROM ClinicExpenses";

        var table = _db.ExecuteQuery(sql);
        var row = table.Rows[0];

        return new ExpenseSummary
        {
            TodayExpense = (decimal)row["TodayExpense"],
            MonthExpense = (decimal)row["MonthExpense"],
            YearExpense = (decimal)row["YearExpense"],
            YesterdayExpense = (decimal)row["YesterdayExpense"],
            LastMonthExpense = (decimal)row["LastMonthExpense"],
            LastYearExpense = (decimal)row["LastYearExpense"]
        };
    }

    // إجمالي عمولات الأطباء فقط (بند "Doctor Commission" من ضمن كل المصاريف) - يومي/شهري/سنوي.
    // يُستخدم لعرض "عمولات الأطباء تمثّل X% من إجمالي المصاريف" بشكل مستقل عن باقي بنود التشغيل
    public CommissionSummary GetCommissionSummary()
    {
        const string sql = @"
            SELECT
                ISNULL(SUM(CASE WHEN CAST(ExpenseDate AS DATE) = CAST(GETDATE() AS DATE) THEN Amount ELSE 0 END), 0) AS TodayCommission,
                ISNULL(SUM(CASE WHEN YEAR(ExpenseDate) = YEAR(GETDATE()) AND MONTH(ExpenseDate) = MONTH(GETDATE()) THEN Amount ELSE 0 END), 0) AS MonthCommission,
                ISNULL(SUM(CASE WHEN YEAR(ExpenseDate) = YEAR(GETDATE()) THEN Amount ELSE 0 END), 0) AS YearCommission
            FROM ClinicExpenses
            WHERE Category = @Cat";

        var table = _db.ExecuteQuery(sql, new SqlParameter("@Cat", DoctorCommissionCategory));
        var row = table.Rows[0];

        return new CommissionSummary
        {
            TodayCommission = (decimal)row["TodayCommission"],
            MonthCommission = (decimal)row["MonthCommission"],
            YearCommission = (decimal)row["YearCommission"]
        };
    }

    public List<ExpenseRow> GetRecentExpenses(int top = 50)
    {
        const string sql = @"
        SELECT TOP (@Top) ExpenseID, Amount, Description, Category, ExpenseDate,
               ISNULL(IsAutoGenerated, 0) AS IsAutoGenerated
        FROM ClinicExpenses 
        ORDER BY ExpenseDate DESC";

        var table = _db.ExecuteQuery(sql, new SqlParameter("@Top", top));
        var result = new List<ExpenseRow>();

        foreach (DataRow row in table.Rows)
        {
            result.Add(new ExpenseRow
            {
                ExpenseID = (int)row["ExpenseID"],
                Amount = (decimal)row["Amount"],
                Description = row["Description"].ToString()!,
                Category = row["Category"] != DBNull.Value ? row["Category"].ToString()! : "General / Other",
                ExpenseDate = (DateTime)row["ExpenseDate"],
                IsAutoGenerated = (bool)row["IsAutoGenerated"]
            });
        }
        return result;
    }

    // حذف مصروف (يدوي أو عمولة تلقائية على حدٍ سواء) - يُستخدم لتصحيح الأخطاء من شاشة الفاينانس
    public void DeleteExpense(int expenseId)
    {
        const string sql = "DELETE FROM ClinicExpenses WHERE ExpenseID = @ExpenseID";
        _db.ExecuteNonQuery(sql, new SqlParameter("@ExpenseID", expenseId));
    }

    // دالة لحساب الربح الصافي (مثلاً لهذا الشهر)
    public NetProfitSummary GetMonthNetProfit()
    {
        const string sql = @"
            DECLARE @Income DECIMAL(18,2) = (SELECT ISNULL(SUM(Amount), 0) FROM Payments WHERE YEAR(PaymentDate) = YEAR(GETDATE()) AND MONTH(PaymentDate) = MONTH(GETDATE()));
            DECLARE @Expense DECIMAL(18,2) = (SELECT ISNULL(SUM(Amount), 0) FROM ClinicExpenses WHERE YEAR(ExpenseDate) = YEAR(GETDATE()) AND MONTH(ExpenseDate) = MONTH(GETDATE()));
            SELECT @Income AS TotalIncome, @Expense AS TotalExpense;";

        var table = _db.ExecuteQuery(sql);
        var row = table.Rows[0];

        return new NetProfitSummary
        {
            TotalIncome = (decimal)row["TotalIncome"],
            TotalExpense = (decimal)row["TotalExpense"]
        };
    }
    // دالة جلب وتجميع بيانات المخطط البياني حسب الفترة (Weekly / Monthly / Yearly)
    public List<FinancialChartItem> GetFinancialChartData(string period)
    {
        var result = new List<FinancialChartItem>();

        if (period == "Weekly")
        {
            var startDate = DateTime.Now.Date.AddDays(-6);

            const string incomeSql = @"
            SELECT CAST(PaymentDate AS DATE) AS TransDate, ISNULL(SUM(Amount), 0) AS Total
            FROM Payments
            WHERE CAST(PaymentDate AS DATE) >= @FromDate
            GROUP BY CAST(PaymentDate AS DATE)";

            const string expenseSql = @"
            SELECT CAST(ExpenseDate AS DATE) AS TransDate, ISNULL(SUM(Amount), 0) AS Total
            FROM ClinicExpenses
            WHERE CAST(ExpenseDate AS DATE) >= @FromDate
            GROUP BY CAST(ExpenseDate AS DATE)";

            var incomeTable = _db.ExecuteQuery(incomeSql, new SqlParameter("@FromDate", startDate));
            var expenseTable = _db.ExecuteQuery(expenseSql, new SqlParameter("@FromDate", startDate));

            var incomeDict = incomeTable.Rows.Cast<DataRow>()
                .ToDictionary(r => ((DateTime)r["TransDate"]).Date, r => (decimal)r["Total"]);
            var expenseDict = expenseTable.Rows.Cast<DataRow>()
                .ToDictionary(r => ((DateTime)r["TransDate"]).Date, r => (decimal)r["Total"]);

            for (int i = 6; i >= 0; i--)
            {
                var date = DateTime.Now.Date.AddDays(-i);
                decimal inc = incomeDict.TryGetValue(date, out var v1) ? v1 : 0;
                decimal exp = expenseDict.TryGetValue(date, out var v2) ? v2 : 0;

                result.Add(new FinancialChartItem
                {
                    Label = date.ToString("ddd"),
                    Income = inc,
                    Expense = exp
                });
            }
        }
        else if (period == "Monthly")
        {
            var startDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).AddMonths(-5);

            const string incomeSql = @"
            SELECT YEAR(PaymentDate) AS Yr, MONTH(PaymentDate) AS Mth, ISNULL(SUM(Amount), 0) AS Total
            FROM Payments
            WHERE PaymentDate >= @FromDate
            GROUP BY YEAR(PaymentDate), MONTH(PaymentDate)";

            const string expenseSql = @"
            SELECT YEAR(ExpenseDate) AS Yr, MONTH(ExpenseDate) AS Mth, ISNULL(SUM(Amount), 0) AS Total
            FROM ClinicExpenses
            WHERE ExpenseDate >= @FromDate
            GROUP BY YEAR(ExpenseDate), MONTH(ExpenseDate)";

            var incomeTable = _db.ExecuteQuery(incomeSql, new SqlParameter("@FromDate", startDate));
            var expenseTable = _db.ExecuteQuery(expenseSql, new SqlParameter("@FromDate", startDate));

            var incomeDict = incomeTable.Rows.Cast<DataRow>()
                .ToDictionary(r => $"{r["Yr"]}-{r["Mth"]}", r => (decimal)r["Total"]);
            var expenseDict = expenseTable.Rows.Cast<DataRow>()
                .ToDictionary(r => $"{r["Yr"]}-{r["Mth"]}", r => (decimal)r["Total"]);

            for (int i = 5; i >= 0; i--)
            {
                var targetMonth = DateTime.Now.AddMonths(-i);
                string key = $"{targetMonth.Year}-{targetMonth.Month}";

                decimal inc = incomeDict.TryGetValue(key, out var v1) ? v1 : 0;
                decimal exp = expenseDict.TryGetValue(key, out var v2) ? v2 : 0;

                result.Add(new FinancialChartItem
                {
                    Label = targetMonth.ToString("MMM"),
                    Income = inc,
                    Expense = exp
                });
            }
        }
        else if (period == "Yearly")
        {
            int startYear = DateTime.Now.Year - 4;

            const string incomeSql = @"
            SELECT YEAR(PaymentDate) AS Yr, ISNULL(SUM(Amount), 0) AS Total
            FROM Payments
            WHERE YEAR(PaymentDate) >= @StartYear
            GROUP BY YEAR(PaymentDate)";

            const string expenseSql = @"
            SELECT YEAR(ExpenseDate) AS Yr, ISNULL(SUM(Amount), 0) AS Total
            FROM ClinicExpenses
            WHERE YEAR(ExpenseDate) >= @StartYear
            GROUP BY YEAR(ExpenseDate)";

            var incomeTable = _db.ExecuteQuery(incomeSql, new SqlParameter("@StartYear", startYear));
            var expenseTable = _db.ExecuteQuery(expenseSql, new SqlParameter("@StartYear", startYear));

            var incomeDict = incomeTable.Rows.Cast<DataRow>()
                .ToDictionary(r => (int)r["Yr"], r => (decimal)r["Total"]);
            var expenseDict = expenseTable.Rows.Cast<DataRow>()
                .ToDictionary(r => (int)r["Yr"], r => (decimal)r["Total"]);

            for (int i = 4; i >= 0; i--)
            {
                int year = DateTime.Now.Year - i;
                decimal inc = incomeDict.TryGetValue(year, out var v1) ? v1 : 0;
                decimal exp = expenseDict.TryGetValue(year, out var v2) ? v2 : 0;

                result.Add(new FinancialChartItem
                {
                    Label = year.ToString(),
                    Income = inc,
                    Expense = exp
                });
            }
        }

        // حساب الارتفاعات ديناميكياً للنسب المئوية للأعمدة
        decimal maxAmount = result.Count > 0 ? result.Max(x => Math.Max(x.Income, x.Expense)) : 0;
        double maxBarHeight = 170.0;

        foreach (var item in result)
        {
            item.IncomeBarHeight = maxAmount > 0 ? (double)(item.Income / maxAmount) * maxBarHeight : 0;
            item.ExpenseBarHeight = maxAmount > 0 ? (double)(item.Expense / maxAmount) * maxBarHeight : 0;
        }

        return result;
    }
}
