/****** Object:  Table [dbo].[ClinicExpenses]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ClinicExpenses](
	[ExpenseID] [int] IDENTITY(1,1) NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[Description] [nvarchar](500) NOT NULL,
	[ExpenseDate] [datetime] NOT NULL,
	[Category] [nvarchar](100) NOT NULL,
	[IsAutoGenerated] [bit] NOT NULL,
	[SourceSessionID] [int] NULL,
	[SourcePaymentID] [int] NULL,
	[SourceDoctorUserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ExpenseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ClinicSettings]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ClinicSettings](
	[SettingKey] [nvarchar](100) NOT NULL,
	[SettingValue] [nvarchar](1000) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SettingKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MedicalSessions]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MedicalSessions](
	[SessionID] [int] IDENTITY(1,1) NOT NULL,
	[VisitID] [int] NULL,
	[PatientID] [int] NOT NULL,
	[DoctorID] [int] NOT NULL,
	[SessionDateTime] [datetime] NOT NULL,
	[ChiefComplaint] [nvarchar](500) NULL,
	[Diagnosis] [nvarchar](1000) NULL,
	[TreatmentPerformed] [nvarchar](1000) NULL,
	[Medication] [nvarchar](500) NULL,
	[Certificate] [nvarchar](max) NULL,
	[TotalPrice] [decimal](10, 2) NOT NULL,
	[PaidAmount] [decimal](10, 2) NOT NULL,
	[WriteOffAmount] [decimal](10, 2) NOT NULL CONSTRAINT [DF_MedicalSessions_WriteOffAmount] DEFAULT ((0)),
	[RemainingAmount]  AS ([TotalPrice]-[PaidAmount]-[WriteOffAmount]) PERSISTED,
	[Notes] [nvarchar](1000) NULL,
	[RowVersion] [rowversion] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SessionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MedicationPresets]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MedicationPresets](
	[MedicationID] [int] IDENTITY(1,1) NOT NULL,
	[MedicationName] [nvarchar](200) NOT NULL,
	[DefaultDosage] [nvarchar](200) NULL,
	[DefaultDuration] [nvarchar](200) NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MedicationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CertificatePresets] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CertificatePresets](
	[CertificateID] [int] IDENTITY(1,1) NOT NULL,
	[CertificateName] [nvarchar](200) NOT NULL,
	[DefaultText] [nvarchar](max) NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CertificateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Patients]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patients](
	[PatientID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](150) NOT NULL,
	[Age] [int] NULL,
	[Gender] [nvarchar](10) NULL,
	[PhoneNumber] [nvarchar](20) NOT NULL,
	[Address] [nvarchar](250) NULL,
	[BasicMedicalNotes] [nvarchar](500) NULL,
	[RegisteredByUserID] [int] NOT NULL,
	[RegisteredAt] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[AssignedDoctorUserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PatientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Payments]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Payments](
	[PaymentID] [int] IDENTITY(1,1) NOT NULL,
	[SessionID] [int] NOT NULL,
	[Amount] [decimal](10, 2) NOT NULL,
	[PaymentDate] [datetime] NOT NULL,
	[ReceivedByUserID] [int] NOT NULL,
	[Notes] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[PaymentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissions]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissions](
	[PermissionKey] [nvarchar](50) NOT NULL,
	[Category] [nvarchar](50) NOT NULL,
	[DisplayName] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](255) NULL,
	[SortOrder] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PermissionKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[RoleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ToothRecords]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ToothRecords](
	[ToothRecordID] [int] IDENTITY(1,1) NOT NULL,
	[SessionID] [int] NOT NULL,
	[ToothNumber] [nvarchar](5) NOT NULL,
	[ToothCondition] [nvarchar](50) NOT NULL,
	[ProcedureNotes] [nvarchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[ToothRecordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TreatmentPresets]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TreatmentPresets](
	[TreatmentID] [int] IDENTITY(1,1) NOT NULL,
	[TreatmentName] [nvarchar](200) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TreatmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserPermissions]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserPermissions](
	[UserID] [int] NOT NULL,
	[PermissionKey] [nvarchar](50) NOT NULL,
	[IsGranted] [bit] NOT NULL,
 CONSTRAINT [PK_UserPermissions] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[PermissionKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[RoleID] [int] NOT NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
	[LastLoginAt] [datetime] NULL,
	[IsAdmin] [bit] NOT NULL,
	[PermissionsMask] [int] NOT NULL,
	[CommissionPercent] [decimal](5, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VisitQueue]    Script Date: 04/08/2026 08:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VisitQueue](
	[VisitID] [int] IDENTITY(1,1) NOT NULL,
	[PatientID] [int] NOT NULL,
	[VisitDate] [date] NOT NULL,
	[CheckInTime] [datetime] NOT NULL,
	[Status] [nvarchar](20) NOT NULL,
	[CreatedByUserID] [int] NOT NULL,
	[StatusUpdatedAt] [datetime] NULL,
	[StatusUpdatedByUserID] [int] NULL,
	[ScheduledDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[VisitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Sessions_Patient]    Script Date: 04/08/2026 08:19:55 ******/
CREATE NONCLUSTERED INDEX [IX_Sessions_Patient] ON [dbo].[MedicalSessions]
(
	[PatientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Patients_FullName]    Script Date: 04/08/2026 08:19:55 ******/
CREATE NONCLUSTERED INDEX [IX_Patients_FullName] ON [dbo].[Patients]
(
	[FullName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Patients_Phone]    Script Date: 04/08/2026 08:19:55 ******/
CREATE NONCLUSTERED INDEX [IX_Patients_Phone] ON [dbo].[Patients]
(
	[PhoneNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Queue_Status_Date]    Script Date: 04/08/2026 08:19:55 ******/
CREATE NONCLUSTERED INDEX [IX_Queue_Status_Date] ON [dbo].[VisitQueue]
(
	[Status] ASC,
	[VisitDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ClinicExpenses] ADD  DEFAULT (getdate()) FOR [ExpenseDate]
GO
ALTER TABLE [dbo].[ClinicExpenses] ADD  DEFAULT (N'General / Other') FOR [Category]
GO
ALTER TABLE [dbo].[ClinicExpenses] ADD  DEFAULT ((0)) FOR [IsAutoGenerated]
GO
ALTER TABLE [dbo].[MedicalSessions] ADD  DEFAULT (getdate()) FOR [SessionDateTime]
GO
ALTER TABLE [dbo].[MedicalSessions] ADD  DEFAULT ((0)) FOR [TotalPrice]
GO
ALTER TABLE [dbo].[MedicalSessions] ADD  DEFAULT ((0)) FOR [PaidAmount]
GO
ALTER TABLE [dbo].[MedicalSessions] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[MedicationPresets] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Patients] ADD  DEFAULT (getdate()) FOR [RegisteredAt]
GO
ALTER TABLE [dbo].[Patients] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Payments] ADD  DEFAULT (getdate()) FOR [PaymentDate]
GO
ALTER TABLE [dbo].[Permissions] ADD  DEFAULT ((0)) FOR [SortOrder]
GO
ALTER TABLE [dbo].[TreatmentPresets] ADD  DEFAULT ((0)) FOR [Price]
GO
ALTER TABLE [dbo].[TreatmentPresets] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[UserPermissions] ADD  DEFAULT ((0)) FOR [IsGranted]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((0)) FOR [IsAdmin]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((0)) FOR [PermissionsMask]
GO
ALTER TABLE [dbo].[VisitQueue] ADD  DEFAULT (CONVERT([date],getdate())) FOR [VisitDate]
GO
ALTER TABLE [dbo].[VisitQueue] ADD  DEFAULT (getdate()) FOR [CheckInTime]
GO
ALTER TABLE [dbo].[VisitQueue] ADD  DEFAULT (N'Waiting') FOR [Status]
GO
ALTER TABLE [dbo].[VisitQueue] ADD  DEFAULT (getdate()) FOR [ScheduledDate]
GO
ALTER TABLE [dbo].[MedicalSessions]  WITH CHECK ADD  CONSTRAINT [FK_Session_Doctor] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[MedicalSessions] CHECK CONSTRAINT [FK_Session_Doctor]
GO
ALTER TABLE [dbo].[MedicalSessions]  WITH CHECK ADD  CONSTRAINT [FK_Session_Patient] FOREIGN KEY([PatientID])
REFERENCES [dbo].[Patients] ([PatientID])
GO
ALTER TABLE [dbo].[MedicalSessions] CHECK CONSTRAINT [FK_Session_Patient]
GO
ALTER TABLE [dbo].[MedicalSessions]  WITH CHECK ADD  CONSTRAINT [FK_Session_Visit] FOREIGN KEY([VisitID])
REFERENCES [dbo].[VisitQueue] ([VisitID])
GO
ALTER TABLE [dbo].[MedicalSessions] CHECK CONSTRAINT [FK_Session_Visit]
GO
ALTER TABLE [dbo].[Patients]  WITH CHECK ADD  CONSTRAINT [FK_Patients_Users] FOREIGN KEY([RegisteredByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Patients] CHECK CONSTRAINT [FK_Patients_Users]
GO
ALTER TABLE [dbo].[Payments]  WITH CHECK ADD  CONSTRAINT [FK_Payment_Session] FOREIGN KEY([SessionID])
REFERENCES [dbo].[MedicalSessions] ([SessionID])
GO
ALTER TABLE [dbo].[Payments] CHECK CONSTRAINT [FK_Payment_Session]
GO
ALTER TABLE [dbo].[Payments]  WITH CHECK ADD  CONSTRAINT [FK_Payment_User] FOREIGN KEY([ReceivedByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Payments] CHECK CONSTRAINT [FK_Payment_User]
GO
ALTER TABLE [dbo].[ToothRecords]  WITH CHECK ADD  CONSTRAINT [FK_Tooth_Session] FOREIGN KEY([SessionID])
REFERENCES [dbo].[MedicalSessions] ([SessionID])
GO
ALTER TABLE [dbo].[ToothRecords] CHECK CONSTRAINT [FK_Tooth_Session]
GO
ALTER TABLE [dbo].[UserPermissions]  WITH CHECK ADD  CONSTRAINT [FK_UserPermissions_Permissions] FOREIGN KEY([PermissionKey])
REFERENCES [dbo].[Permissions] ([PermissionKey])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserPermissions] CHECK CONSTRAINT [FK_UserPermissions_Permissions]
GO
ALTER TABLE [dbo].[UserPermissions]  WITH CHECK ADD  CONSTRAINT [FK_UserPermissions_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserPermissions] CHECK CONSTRAINT [FK_UserPermissions_Users]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Roles] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([RoleID])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Roles]
GO
ALTER TABLE [dbo].[VisitQueue]  WITH CHECK ADD  CONSTRAINT [FK_Queue_CreatedBy] FOREIGN KEY([CreatedByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[VisitQueue] CHECK CONSTRAINT [FK_Queue_CreatedBy]
GO
ALTER TABLE [dbo].[VisitQueue]  WITH CHECK ADD  CONSTRAINT [FK_Queue_Patient] FOREIGN KEY([PatientID])
REFERENCES [dbo].[Patients] ([PatientID])
GO
ALTER TABLE [dbo].[VisitQueue] CHECK CONSTRAINT [FK_Queue_Patient]
GO
ALTER TABLE [dbo].[VisitQueue]  WITH CHECK ADD  CONSTRAINT [FK_Queue_UpdatedBy] FOREIGN KEY([StatusUpdatedByUserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[VisitQueue] CHECK CONSTRAINT [FK_Queue_UpdatedBy]
GO
ALTER TABLE [dbo].[Patients]  WITH CHECK ADD CHECK  (([Age]>=(0) AND [Age]<=(130)))
GO
ALTER TABLE [dbo].[Patients]  WITH CHECK ADD CHECK  (([Gender]=N'Female' OR [Gender]=N'Male'))
GO
ALTER TABLE [dbo].[VisitQueue]  WITH CHECK ADD  CONSTRAINT [CK_VisitQueue_Status] CHECK  (([Status]='Scheduled' OR [Status]='Cancelled' OR [Status]='Completed' OR [Status]='InTreatment' OR [Status]='Waiting'))
GO
ALTER TABLE [dbo].[VisitQueue] CHECK CONSTRAINT [CK_VisitQueue_Status]
GO

/****** Seed data: Roles (Doctor=1, Nurse=2 - required to match hardcoded RoleID in UserRepository.AddUser) ******/
INSERT INTO dbo.Roles (RoleName) VALUES (N'Doctor');
GO
INSERT INTO dbo.Roles (RoleName) VALUES (N'Nurse');
GO
